id: I8C160AAF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T19:30:13+00:00'
last_modified: '2022-06-08T13:46:54.644668+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19996
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་ལས་ཞི་ཁྲོའི་ལས་བྱང་ཤིན་ཏུ་མདོར་བསྡུས་པ་གཏོར་སྒྲུབ་རང་གྲོལ་སྙིང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7F2E:
      image_group_id: I8LS19998
      title: ''
      total_pages: 120
      order: 1
      base_file: 7F2E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
